version: "3.9"

services:
  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  engine:
    build:
      context: ./engine
      dockerfile: Dockerfile
    container_name: engine
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./engine:/app
    ports:
      - "50051:50051"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: always
    depends_on:
      - redis
      - engine
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ENGINE_TARGET=engine:50051
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

volumes:
  redis_data: