# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proto/lob.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app/proto/lob.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61pp/proto/lob.proto\x12\x06orders\"\x1c\n\nLobRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\".\n\nPriceLevel\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x11\n\ttotal_qty\x18\x02 \x01(\x05\"a\n\x0bLobResponse\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12 \n\x04\x62ids\x18\x02 \x03(\x0b\x32\x12.orders.PriceLevel\x12 \n\x04\x61sks\x18\x03 \x03(\x0b\x32\x12.orders.PriceLevel\"M\n\x0cOrderRequest\x12\x0e\n\x06tikcer\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x10\n\x08quantity\x18\x04 \x01(\x05\"O\n\x12ModifyOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x03\x12\x11\n\tnew_price\x18\x02 \x01(\x01\x12\x14\n\x0cnew_quantity\x18\x03 \x01(\x05\"&\n\x12\x43\x61ncelOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x03\"u\n\x05Trade\x12\x11\n\tunique_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x0b\n\x03qty\x18\x04 \x01(\x05\x12\x14\n\x0c\x62id_order_id\x18\x05 \x01(\t\x12\x14\n\x0c\x61sk_order_id\x18\x06 \x01(\t\"P\n\rOrderResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x1d\n\x06trades\x18\x03 \x03(\x0b\x32\r.orders.Trade2\x81\x02\n\x0cOrderService\x12:\n\x0bSubmitOrder\x12\x14.orders.OrderRequest\x1a\x15.orders.OrderResponse\x12@\n\x0bModifyOrder\x12\x1a.orders.ModifyOrderRequest\x1a\x15.orders.OrderResponse\x12@\n\x0b\x43\x61ncelOrder\x12\x1a.orders.CancelOrderRequest\x1a\x15.orders.OrderResponse\x12\x31\n\x06GetLob\x12\x12.orders.LobRequest\x1a\x13.orders.LobResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.proto.lob_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOBREQUEST']._serialized_start=31
  _globals['_LOBREQUEST']._serialized_end=59
  _globals['_PRICELEVEL']._serialized_start=61
  _globals['_PRICELEVEL']._serialized_end=107
  _globals['_LOBRESPONSE']._serialized_start=109
  _globals['_LOBRESPONSE']._serialized_end=206
  _globals['_ORDERREQUEST']._serialized_start=208
  _globals['_ORDERREQUEST']._serialized_end=285
  _globals['_MODIFYORDERREQUEST']._serialized_start=287
  _globals['_MODIFYORDERREQUEST']._serialized_end=366
  _globals['_CANCELORDERREQUEST']._serialized_start=368
  _globals['_CANCELORDERREQUEST']._serialized_end=406
  _globals['_TRADE']._serialized_start=408
  _globals['_TRADE']._serialized_end=525
  _globals['_ORDERRESPONSE']._serialized_start=527
  _globals['_ORDERRESPONSE']._serialized_end=607
  _globals['_ORDERSERVICE']._serialized_start=610
  _globals['_ORDERSERVICE']._serialized_end=867
# @@protoc_insertion_point(module_scope)
